---

ansible_become: true
ansible_become_method: sudo
ansible_user: robertas

common_extra_pkgs:
  - nfs-common

k8s:
  addons:
    # https://github.com/projectcalico/calico/releases
    calico: v3.27.3

  # firewalld:
  #   ports:
  #     - 2379
  #     - 2380
  #     - 5473
  #     - 6443
  #     - 10250
  #     - 10251
  #     - 10252

  network_cidr: 10.32.0.0/16

  # https://kubernetes.io/releases/
  release: "1.30"
  version: "1.30.0"
  apt_version: "1.30.0-1.1"
