---

ansible_become: true
ansible_become_method: sudo
ansible_user: robertas

k8s_cgroup_RedHat: "true"
k8s_cgroup_Ubuntu: "false"

k8s:
  cni:
    select: kube-router

    # https://github.com/projectcalico/calico/releases
    calico:
      version: v3.28.0

    # https://github.com/flannel-io/flannel/releases
    flannel:
      version: v0.25.4

    # https://github.com/cloudnativelabs/kube-router/releases
    kube-router:
      version: v2.2.1

  firewalld:
    ports:
      # Kubernetes https://kubernetes.io/docs/reference/networking/ports-and-protocols/
      - 2379/tcp
      - 2380/tcp
      - 5473/tcp
      - 6443/tcp
      - 10250/tcp
      - 10256/tcp
      - 10257/tcp
      - 10259/tcp
      - 30000-32767/tcp
      # Calico / BGP
      - 179/tcp
      # NFS server
      - 111/tcp
      - 111/udp
      - 2049/tcp
      - 2049/udp
    trusted_sources:
      - 192.168.0.0/16

  network_cidr: 10.32.0.0/16

  # https://kubernetes.io/releases/
  version: "1.30.2"
