---

ansible_become: true
ansible_become_method: sudo

# common
common_apt_extra_pkgs:
  # essentials
  - apt-transport-https
  - bash-completion
  - build-essential
  - kdenlive
  - kubuntu-restricted-extras
  - ncdu
  - okular
  - ostree
  - partitionmanager
  - plasma-discover-backend-flatpak
  - screen
  - vim-nox
  - virt-manager
  - vlc
  # multimedia
  - ffmpeg
  - yt-dlp
  # tools
  - yamllint

flatpak_pkgs:
  - org.chromium.Chromium
  - org.darktable.Darktable
  - org.gimp.GIMP
  - org.inkscape.Inkscape
  - org.kde.krita
  - org.qbittorrent.qBittorrent

# optional software
opt:
  dir: /data/opt
  uid: 1000
  gid: 1000
  user: robertas

# blender
blender:
  release: 4.4
  version: 4.4.0

# hashicorp
hashicorp_pkgs:
  - terraform

# slack
slack:
  version: 4.41.105

# wireguard
wireguard:
  interface:
    address: 172.31.255.3/24
    name: wg0
  peer:
    name: aws
    allowedIPs: 0.0.0.0/0
    endpoint: 13.41.117.97:51820
    keepAlive: 25
