---

ansible_become: true
ansible_become_method: sudo

# common
common_apt_extra_pkgs:
  # essentials
  - apt-transport-https
  - bash-completion
  - build-essential
  - kdenlive
  - kubuntu-restricted-extras
  - ncdu
  - okular
  - ostree
  - partitionmanager
  - plasma-discover-backend-flatpak
  - screen
  - vim-nox
  - virt-manager
  - vlc
  # multimedia
  - ffmpeg
  - yt-dlp
  # tools
  - yamllint

# flatpak
flatpak_pkgs:
  - org.chromium.Chromium
  - org.darktable.Darktable
  - org.gimp.GIMP
  - org.inkscape.Inkscape
  - org.kde.krita
  - org.qbittorrent.qBittorrent

# extra
opt:
  dir: /data/opt
  uid: 1000
  gid: 1000
  user: robertas

# fw
fw:
  dhcp:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    domain: reiciunas.dev
    subnet:
      address: 172.31.0.0
      netmask: 255.255.255.0
      range: 172.31.0.64 172.31.0.91
  interface: enp0s13f0u3u4
  ip: 172.31.0.1
  mask: 24

# k8s
k8s_pkgs:
  - kubectl

# tools:blender
blender:
  release: 4.4
  version: 4.4.0

# tools:hashicorp
hashicorp_pkgs:
  - terraform

# tools:wireguard
wireguard:
  interface:
    address: 172.31.255.3/24
    name: wg0
  peer:
    name: aws
    allowedIPs: 0.0.0.0/0
    endpoint: 13.41.117.97:51820
    keepAlive: 25
