---

# ip addr add 172.31.0.1/24 dev enp0s13f0u3u4
# ip link set enp0s13f0u3u4 up

- name: Sysctl - ip forwarding
  ansible.builtin.import_tasks:
    sysctl.yml

- name: DHCP Server
  ansible.builtin.import_tasks:
    dhcp.yml

# iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
# iptables -A FORWARD -i enp0s13f0u3u4 -o wlp0s20f3 -j ACCEPT
# iptables -t nat -A POSTROUTING -o wlp0s20f3 -j MASQUERADE
