---

- name: firewalld - ports
  firewalld:
    immediate: true
    permanent: true
    port: "{{ item }}"
    state: enabled
  with_items: "{{ k8s.firewalld.ports }}"

- name: firewalld - trusted sources
  firewalld:
    immediate: true
    permanent: true
    source: "{{ item }}"
    state: enabled
    zone: trusted
  with_items: "{{ k8s.firewalld.trusted_sources }}"

- name: firewalld - network_cidr
  firewalld:
    immediate: true
    permanent: true
    source: "{{ item }}"
    state: enabled
    zone: trusted
  with_items: "{{ k8s.network_cidr }}"

- name: systemd - firewalld
  systemd:
    name: firewalld
    enabled: true
    state: restarted
