---

- name: Firewalld - ports
  firewalld:
    immediate: true
    permanent: true
    port: "{{ item }}"
    state: enabled
  with_items: "{{ k8s.firewalld.ports }}"

- name: Firewalld - trusted sources
  firewalld:
    immediate: true
    permanent: true
    source: "{{ item }}"
    state: enabled
    zone: trusted
  with_items: "{{ k8s.firewalld.trusted_sources }}"

- name: Firewalld - network_cidr
  firewalld:
    immediate: true
    permanent: true
    source: "{{ item }}"
    state: enabled
    zone: trusted
  with_items: "{{ k8s.network_cidr }}"

- name: Systemd - firewalld
  ansible.builtin.systemd:
    name: Firewalld
    enabled: true
    state: restarted
