---

- name: firewalld - {{ item }}
  firewalld:
    immediate: true
    permanent: true
    port: "{{ item }}/tcp"
    state: enabled
  with_items: "{{ k8s.firewalld.ports }}"

- name: systemd - firewalld
  systemd:
    name: firewalld
    enabled: true
    state: restarted
