---

# Check state file
- name: stat - /root/.state.cluster.setup
  stat:
    path: /root/.state.cluster.setup
  register: cluster_setup
  tags:
    - always

# System prep
- name: System preparation
  import_tasks:
    system.yml
  tags:
    - system
  when: not cluster_setup.stat.exists

# Install containerd.io
- name: Intall containerd.io
  import_tasks:
    containerd.yml
  tags:
    - containerd
  when: not cluster_setup.stat.exists

# Reboot, if first time running
- name: reboot
  reboot: {}
  when: not cluster_setup.stat.exists

# Install K8s
- name: Intall k8s
  import_tasks:
    k8s.yml
  tags:
    - k8s

# Setup FirewallD
- name: firewalld rules
  import_tasks:
    firewall.yml
  tags:
    - firewall
    - firewalld
  when: "ansible_distribution == 'RedHat'"

# Touch state file
- name: file - touch /root/.state.cluster.setup
  file:
    path: /root/.state.cluster.setup
    state: touch
