---

# Kernel modules
- name: copy - /etc/modules-load.d/containerd.conf
  copy:
    src: etc/modules-load.d/containerd.conf
    dest: /etc/modules-load.d/containerd.conf

# Sysctl config
- name: copy - /etc/sysctl.d/99-kubernetes-cri.conf
  copy:
    src: etc/sysctl.d/99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

# Swap off
- name: Lineinfile - .*swap.*
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regex: '^#?(.*swap.*)'
    line: '#\1'
    backrefs: true

- name: Shell - swapoff -a
  ansible.builtin.shell: swapoff -a

- name: File - /swap.img
  ansible.builtin.file:
    path: /swap.img
    state: absent
  when: "ansible_distribution == 'Ubuntu'"

# TBD: Swap for RedHat

# TBD: SElinux
- name: Lineinfile - SELINUX=permissive
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regex: '^SELINUX=.*'
    line: 'SELINUX=permissive'
  when: "ansible_distribution == 'RedHat'"
