---

# Reset kubeadm and print output
- name: shell - kubeadm reset --force
  shell: kubeadm reset --force
  register: kube_reset_status
  ignore_errors: true

- debug: msg="{{ kube_reset_status.stdout_lines }}"

- debug: msg="{{ kube_reset_status.stderr_lines }}"

# Remove packages
- name: dpkg_selections - hold
  dpkg_selections:
    name: "{{ item }}"
    selection: purge
  with_items:
    - kubeadm
    - kubectl
    - kubelet
  when: "ansible_distribution == 'Ubuntu'"

- name: apt - kubeadm kubectl kubelet
  apt:
    name:
      - containerd.io
      - kubeadm
      - kubectl
      - kubelet
    state: absent
  when: "ansible_distribution == 'Ubuntu'"

- name: dnf - kubeadm kubectl kubelet
  dnf:
    name:
      - containerd.io
      - kubeadm
      - kubectl
      - kubelet
    state: absent
  when: "ansible_distribution == 'RedHat'"

# Remove files and directories
- name: file - loop pkgs files and dirs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cni
    - /etc/kubernetes
    - /opt/cni
    - /opt/containerd
    - /var/lib/containerd
    - /var/lib/containers
    - /var/log/calico
    - /var/log/pods

- name: file - loop state files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/.state.cluster.setup
    - /root/.state.cluster.init
    - /root/.state.cluster.joined
