---

# Reset kubeadm and print output
- name: shell - kubeadm reset --force
  shell: kubeadm reset --force
  register: kube_reset_status

- debug: msg="{{ kube_reset_status.stdout_lines }}"

- debug: msg="{{ kube_reset_status.stderr_lines }}"

# Remove state files
- name: file - rm /root/.state.cluster.setup
  file:
    path: /root/.state.cluster.setup
    state: absent

- name: file - rm /root/.state.cluster.init
  file:
    path: /root/.state.cluster.init
    state: absent
  when: "'control' in group_names"

- name: file - rm /root/.state.cluster.joined
  file:
    path: /root/.state.cluster.joined
    state: absent
  when: "'worker' in group_names"
