---

- name: Facts
  hosts: k8s
  tasks: []
  tags:
    - always

- name: Common
  hosts: k8s
  roles:
    - k8s/setup
  tags:
    - k8s
    - setup

- name: K8s init
  hosts: control
  roles:
    - k8s/init
  tags:
    - init
    - k8s

- name: K8s CNI
  hosts: control
  roles:
    - k8s/cni
  tags:
    - cni
    - k8s

- name: K8s join
  hosts: k8s
  roles:
    - k8s/join
  tags:
    - join
    - k8s

- name: NFS server
  hosts: nfs
  roles:
    - nfs
  tags:
    - nfs
