---

- name: Workstation - common
  hosts: workstation
  connection: local
  roles:
    - common/apt
  tags:
    # - always
    - common

- name: Workstation - flatpak
  hosts: workstation
  connection: local
  roles:
    - flatpak
  tags:
    - flatpak

- name: Workstation - browsers:brave
  hosts: workstation
  connection: local
  roles:
    - browsers/brave/apt
  tags:
    - browsers
    - browsers:brave

- name: Workstation - browsers:chrome
  hosts: workstation
  connection: local
  roles:
    - browsers/chrome/apt
  tags:
    - browsers
    - browsers:chrome

- name: Workstation - browsers:edge
  hosts: workstation
  connection: local
  roles:
    - browsers/edge/apt
  tags:
    - browsers
    - browsers:edge

- name: Workstation - browsers:firefox
  hosts: workstation
  connection: local
  roles:
    - browsers/firefox/apt
  tags:
    - browsers
    - browsers:firefox

- name: Workstation - tools:docker
  hosts: workstation
  connection: local
  roles:
    - docker/apt
  tags:
    - tools
    - tools:docker

- name: Workstation - tools:hashicorp
  hosts: workstation
  connection: local
  roles:
    - hashicorp/apt
  tags:
    - tools
    - tools:hashicorp

- name: Workstation - tools:helm
  hosts: workstation
  connection: local
  roles:
    - helm/apt
  tags:
    - tools
    - tools:helm

- name: Workstation - tools:vscode
  hosts: workstation
  connection: local
  roles:
    - vscode/apt
  tags:
    - tools
    - tools:vscode

- name: Workstation - tools:wireguard
  hosts: workstation
  connection: local
  roles:
    - wireguard
  tags:
    - tools
    - tools:wireguard

- name: Workstation - sw:blender
  hosts: workstation
  connection: local
  roles:
    - blender
  tags:
    - sw
    - sw:blender

- name: Workstation - sw:slack
  hosts: workstation
  connection: local
  roles:
    - slack
  tags:
    - sw
    - sw:slack
