---

- name: Get_url - google-chrome signing key
  ansible.builtin.get_url:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/trusted.gpg.d/google.asc
    mode: "0644"
    force: true

- name: Apt_repository - google-chrome
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/google.asc] https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present
    update_cache: true

- name: Apt - google-chrome packages
  ansible.builtin.apt:
    pkg:
      - google-chrome-stable
    state: present
