---

- name: Get_url - helm key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /tmp/helm.asc
    mode: "0644"

- name: Shell - gpg dearmor
  ansible.builtin.shell: cat /tmp/helm.asc | gpg --dearmor > /usr/share/keyrings/helm.gpg

- name: Apt_repository - helm
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
    filename: kubernetes
    state: present

- name: Apt - helm packages
  ansible.builtin.apt:
    pkg:
      - helm
    state: present
    update_cache: true

- name: Shell - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  ansible.builtin.shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Shell - helm repo update
  ansible.builtin.shell: helm repo update
