---

# Apply Calico CNI
- name: Shell - kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.cni.calico.version }}/manifests/calico.yaml
  ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.cni.calico.version }}/manifests/calico.yaml
  delay: 5
  retries: 30
