---

# CNI: Calico
- name: K8s CNI - Calico
  ansible.builtin.import_tasks:
    cni.calico.yml
  when: k8s.cni.select == 'calico'

# CNI: Flannel
- name: K8s CNI - Flannel
  ansible.builtin.import_tasks:
    cni.flannel.yml
  when: k8s.cni.select == 'flannel'

# CNI: kube-router
- name: K8s CNI - kube-router
  ansible.builtin.import_tasks:
    cni.kube-router.yml
  when: k8s.cni.select == 'kube-router'
