---

- name: shell - dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: dnf - docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: user - add to docker group
  user:
    append: true
    groups: docker
    name: "{{ lookup('env', 'USER') }}"
