---

- name: Get_url - brave signing key
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: "0644"
    force: true

- name: Apt_repository - brave
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
    filename: brave-browser-release
    state: present
    update_cache: true

- name: Apt - brave packages
  ansible.builtin.apt:
    pkg:
      - brave-browser
    state: present
