---

- name: template - .bashrc
  template:
    src: .bashrc.j2
    dest: /root/.bashrc
    mode: 0600
  when: "ansible_distribution == 'Debian'"

- name: template - .bash_aliases
  template:
    src: .bash_aliases.j2
    dest: /root/.bash_aliases
    mode: 0600
  when: "ansible_distribution == 'Ubuntu'"

- name: template - .vimrc
  template:
    src: .vimrc.j2
    dest: /root/.vimrc
    mode: 0600

- name: template - .bash_aliases
  template:
    src: .bash_aliases.j2
    dest: /home/{{ ansible_user }}/.bash_aliases
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: "ansible_user != 'root'"
