---

- name: Lineinfile - ~/{{ user_bash_file }}
  ansible.builtin.lineinfile:
    path: ~/{{ user_bash_file }}
    regex: '^export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin'
    line: export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin

- name: Homebrew - update && upgrade
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Homebrew - pkgs
  community.general.homebrew:
    name: "{{ brew_pkgs }}"
