---

- name: lineinfile - ~/{{ user_bash_file }} - brew
  lineinfile:
    path: ~/{{ user_bash_file }}
    regex: '^export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin'
    line: export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin

- name: homebrew - update && upgrade
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: homebrew - pkgs
  community.general.homebrew:
    name: "{{ brew_pkgs }}"
