---

- name: Shell - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  ansible.builtin.shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

- name: Dnf - {{ dnf_hashicorp_pkgs }}
  ansible.builtin.dnf:
    name: "{{ dnf_hashicorp_pkgs }}"
    state: present
