---

- name: File - {{ opt.dir }}
  ansible.builtin.file:
    path: "{{ opt.dir }}"
    owner: "{{ opt.uid }}"
    group: "{{ opt.gid }}"
    mode: "2755"
    state: directory

- name: Get_url - blender archive
  ansible.builtin.get_url:
    url: https://mirrors.dotsrc.org/blender/release/Blender{{ blender.release }}/blender-{{ blender.version }}-linux-x64.tar.xz
    dest: "{{ opt.dir }}/blender-{{ blender.version }}-linux-x64.tar.xz"
    mode: "0644"
    owner: "{{ opt.uid }}"

- name: Unarchive - blender archive
  ansible.builtin.unarchive:
    src: "{{ opt.dir }}/blender-{{ blender.version }}-linux-x64.tar.xz"
    dest: "{{ opt.dir }}"
    owner: "{{ opt.uid }}"

- name: File - symlink ~/bin/blender
  become_user: "{{ opt.user }}"
  ansible.builtin.file:
    src: "{{ opt.dir }}/blender-{{ blender.version }}-linux-x64/blender"
    dest: "~/bin/blender"
    state: link
