---

# up-to-date
- name: Yum - upgrade
  ansible.builtin.yum:
    name: "*"
    state: latest

# Install common packages
- name: Yum - common packages
  ansible.builtin.yum:
    name: "{{ common_yum_pkgs }}"
    state: present
  when: common_yum_pkgs is defined

# Install common extra packages
- name: Yum - common extra packages
  ansible.builtin.yum:
    name: "{{ common_yum_extra_pkgs }}"
    state: present
  when: common_yum_extra_pkgs is defined

# Cleanup yum
- name: Yum - autoremove
  ansible.builtin.yum:
    autoremove: true
