---

- name: Get_url - slack
  ansible.builtin.get_url:
    url: https://downloads.slack-edge.com/desktop-releases/linux/x64/{{ slack.version }}/slack-desktop-{{ slack.version }}-amd64.deb
    dest: "{{ opt.dir }}/slack-desktop-{{ slack.version }}-amd64.deb"
    mode: "0644"
    owner: "{{ opt.uid }}"

- name: Apt - slack
  ansible.builtin.apt:
    deb: "{{ opt.dir }}/slack-desktop-{{ slack.version }}-amd64.deb"
