---

# Init kube cluster
- name: shell - kubeadm init --pod-network-cidr {{ k8s.network_cidr }} --kubernetes-version {{ k8s.version }}
  shell: kubeadm init --pod-network-cidr {{ k8s.network_cidr }} --kubernetes-version {{ k8s.version }}
  register: kubeadm_init_output

- debug: msg="{{ kubeadm_init_output.stdout_lines }}"

- debug: msg="{{ kubeadm_init_output.stderr_lines }}"

# Touch state file
- name: file - touch /root/.state.cluster.init
  file:
    path: /root/.state.cluster.init
    state: touch

# Setup kube config for root
- name: file - /root/.kube
  file:
    path: /root/.kube
    state: directory

- name: copy - /etc/kubernetes/admin.conf /root/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: 0600
    remote_src: true

# Setup kube config for ansible_user
- name: file - /home/{{ ansible_user }}/.kube
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: "ansible_user != 'root'"

- name: copy - /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: "ansible_user != 'root'"

# Pause to become ready
- name: pause - 15s
  pause:
    seconds: 15

# Calico CNI
- name: shell - kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.addons.calico }}/manifests/calico.yaml
  shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.addons.calico }}/manifests/calico.yaml

# - name: shell - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.addons.calico }}/manifests/tigera-operator.yaml
#   shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.addons.calico }}/manifests/tigera-operator.yaml

# - name: get_url - https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.addons.calico }}/manifests/custom-resources.yaml
#   get_url:
#     url: https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.addons.calico }}/manifests/custom-resources.yaml
#     dest: /tmp/custom-resources.yaml

# - name: shell - sed /tmp/custom-resources.yaml
#   shell: "sed -s -i 's|cidr: 192.168.0.0/16|cidr: {{ k8s.network_cidr }}|g' /tmp/custom-resources.yaml"

# - name: shell - kubectl create -f /tmp/custom-resources.yaml
#   shell: kubectl create -f /tmp/custom-resources.yaml
