---

# Check state file
- name: stat - /root/.state.cluster.init
  stat:
    path: /root/.state.cluster.init
  register: cluster_init

# Init cluster
- name: K8s Cluster Init
  import_tasks:
    cluster.init.yml
  when: not cluster_init.stat.exists

# Fetch kube config to running machine
- name: fetch /etc/kubernetes/admin.conf ~/.kube/config
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: true
  tags:
    - kube-config
  when: "'control' in group_names"

# Get and print nodes
- name: shell - kubectl get nodes
  shell: kubectl get nodes
  delay: 5
  register: nodes
  retries: 30

- debug: msg={{ nodes.stdout_lines }}
