---

# Check state file
- name: Stat - /root/.state.cluster.init
  ansible.builtin.stat:
    path: /root/.state.cluster.init
  register: cluster_init

# Init cluster
- name: K8s Cluster Init
  ansible.builtin.import_tasks:
    cluster.init.yml
  when: not cluster_init.stat.exists

# Fetch kube config to running machine
- name: Fetch /etc/kubernetes/admin.conf ~/.kube/config
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: true
  tags:
    - kube-config
  when: "'control' in group_names"

# Get and print nodes
- name: Shell - kubectl get nodes
  ansible.builtin.shell: kubectl get nodes
  delay: 5
  register: nodes
  retries: 30

- name: Debug
  ansible.builtin.debug:
    msg: "{{ nodes.stdout_lines }}"
