---

# Install packages
- name: apt - postfix packages
  apt:
    pkg:
      - libsasl2-modules
      - postfix
    state: present

# Configure postfix
- name: shell - postconf
  shell:
    cmd: >
      postconf -e "relayhost = [{{ lookup('ansible.builtin.env', 'AWS_SES_HOST') }}]:587"
      "inet_interfaces = all"
      "smtp_sasl_auth_enable = yes"
      "smtp_sasl_security_options = noanonymous"
      "smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd"
      "smtp_use_tls = yes"
      "smtp_tls_security_level = encrypt"
      "smtp_tls_note_starttls_offer = yes"
      "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 192.168.0.0/23 192.168.68.0/24"
      "smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt"

# Template sasl_passwd
- name: template - /etc/postfix/sasl_passwd
  template:
    dest: /etc/postfix/sasl_passwd
    src: sasl_passwd.j2
    mode: 0600

# Postmap
- name: shell - postmap
  shell:
    cmd: postmap hash:/etc/postfix/sasl_passwd

# Restart posftix
- name: systemd - postfix
  systemd:
    name: postfix
    state: restarted
