---

- name: Yum - install cockpit-pcp
  ansible.builtin.yum:
    name: cockpit-pcp
    state: present

- name: Systemd - cockpit.socket
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
    state: restarted

- name: Systemd - pmlogger.service
  ansible.builtin.systemd:
    name: pmlogger.service
    enabled: true
    state: restarted
