---

- name: apt - nfs-kernel-server
  apt:
    pkg:
      - nfs-kernel-server
    state: present
  when: "ansible_distribution == 'Debian'"

- name: dnf - nfs-utils
  dnf:
    name:
      - nfs-utils
    state: present
  when: "ansible_distribution == 'RedHat'"

- name: systemd - nfs-server
  systemd:
    name: nfs-server
    enabled: true
    state: restarted
  when: "ansible_distribution == 'RedHat'"

- name: file - /data
  file:
    path: /data
    state: directory

- name: file - /data/{{ item.name }}
  file:
    path: /data/{{ item.name }}
    state: directory
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: "{{ nfs }}"

- name: lineinfile - /etc/exports - {{ item.name }}
  lineinfile:
    path: /etc/exports
    regex: '^/data/{{ item.name }}\s+.*'
    line: /data/{{ item.name }} {{ item.net }}(rw,sync,no_subtree_check,no_root_squash)
  loop: "{{ nfs }}"

- name: shell - exportfs -arv
  shell:
    cmd: exportfs -arv
