---

- name: Get_url - microsoft signing key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc

- name: Shell - gpg dearmor
  ansible.builtin.shell: cat /tmp/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft.gpg

- name: Apt_repository - vscode
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present
    update_cache: true

- name: Apt - vscode packages
  ansible.builtin.apt:
    pkg:
      - code
    state: present
