---

- name: Shell - dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Dnf - docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
