---

- name: apt_repository - ceph enterprise
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} enterprise
    filename: ceph
    state: absent
    update_cache: false

- name: apt_repository - ceph no-subscription
  apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} no-subscription
    filename: ceph
    state: present
    update_cache: false

- name: apt_repository - pve-enterprise
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise
    filename: pve-enterprise
    state: absent
    update_cache: false

- name: apt_repository - pve-no-subscription
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
    filename: pve-enterprise
    state: present
    update_cache: false
